### ISSUE TITLE
PWA如何才能生效？

### ISSUE THREAD

**Issue by iceberg211** [wanghairong-i/umi-dva-typescript-mock#1]
hello，小哥。
看着你这个项目学习了很多，我按照你这个目录配置了manifest.json和图标，build之后也生成了service-worker.js，部署之后也无法出现添加至桌面的效果。请问如何生效？

**Comment by ronffy** [comment]
看下 /dist/static 文件夹下是否有 manifest.json 文件，如果有这个文件，那就不能直观的判断什么问题了。
你搞一个 example 的链接吧，不然无法回答你的问题
